# Generated by Django 5.1 on 2024-08-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
