# Generated by Django 5.1 on 2024-08-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_davomat_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='active',
        ),
    ]
