# Generated by Django 5.1 on 2024-08-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_davomat_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
