# Generated by Django 5.1 on 2024-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_davomat_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
